tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/services'

brew 'zsh'
brew 'git'
brew 'httpie'
brew 'jenv'
brew 'nvm'
brew 'openssl'
brew 'rbenv'
brew 'reattach-to-user-namespace'
brew 'ruby-build'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'neovim'
brew 'wget'
brew 'fzf'

cask '1password'
cask 'alfred'
cask 'font-hack-nerd-font
cask 'karabiner-elements'
cask 'licecap'
cask 'temurin'
cask 'ghostty'
