#!/bin/bash

# Per OS deps
## OSX
### Command Line build tools
### homebrew

# General Deps
## tree
## node
## npm
## vim
## python
## rvm (and latest ruby)
## git
## svn
## ack
## bash_completion

GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
RED="\033[31m"
ENDCOLOR="\033[0m"

OS="unkown"
WORK="crowdfavorite"

if [[ `uname` == 'Darwin' ]]; then
	OS='osx'
elif type apt-get &> /dev/null; then
	OS='debian'
elif type yum &> /dev/null; then
	OS='rhel'
fi

echo -e "${YELLOW}  Linking general files...${ENDCOLOR}"
while read location; do

	name=$(basename "$location")

	if [ -d "$HOME/$name" ]; then
		rm -rf "$HOME/$name"
	fi


	echo -e "${BLUE}    $name${ENDCOLOR}"
	ln -nsf "$location" "$HOME/$name"

done < <(find "$HOME/.dotfiles/general" -depth 1)

echo -e "${YELLOW}  Linking $OS files...${ENDCOLOR}"
while read location; do

	name=$(basename "$location")

	if [ -d "$HOME/$name" ]; then
		rm -rf "$HOME/$name"
	fi

	echo -e "${BLUE}    $name${ENDCOLOR}"
	ln -nsf "$location" "$HOME/$name"

done < <(find "$HOME/.dotfiles/os/$OS" -depth 1)

# Link up ST3 config
rm -rf "~/Library/Application Support/Sublime Text 3/Packages/User"
ln -nsf "~/Library/Application Support/Sublime Text 3/Packages/User"  "$HOME/$name"

if [[ $* == *--work* ]]; then
	echo -e "${YELLOW}  Linking $WORK files...${ENDCOLOR}"
	while read location; do

		name=$(basename "$location")

		if [ -d "$HOME/$name" ]; then
			rm -rf "$HOME/$name"
		fi

		echo -e "${BLUE}    $name${ENDCOLOR}"
		ln -nsf "$location" "$HOME/$name"

	done < <(find "$HOME/.dotfiles/work/$WORK" -depth 1)
fi


source ~/.bash_profile
