#!/bin/bash

GREEN="\033[32m"
YELLOW="\033[33m"
BLUE="\033[34m"
RED="\033[31m"
ENDCOLOR="\033[0m"

sudo echo "" # force password entry early

# OSX Command Line Tools
if ! xcode-select -p &> /dev/null; then
  xcode-select --install
fi

if [ ! -e "$HOME/.dotfiles" ]; then
  echo -e "${YELLOW}Cloning the dotfiles repo...${ENDCOLOR}"
  git clone --recursive https://github.com/jondavidjohn/dotfiles.git $HOME/.dotfiles
  echo ""
fi

cd ~/.dotfiles

# Homebrew Install
if ! command -v brew &> /dev/null; then
  echo -e "${YELLOW}Installing Homebrew...${ENDCOLOR}"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  echo ""
fi

# Homebrew Bundle Install
if [ ! -e "$HOME/.brew-bundle-installed" ]; then
  echo -e "${YELLOW}Homebrew Bundle...${ENDCOLOR}"
  brew tap Homebrew/bundle && brew bundle && touch "$HOME/.brew-bundle-installed"
  echo ""
fi

echo ''

echo -e "${YELLOW}H4cking the plan3t...${ENDCOLOR}"
current_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
while read location; do

  name=$(basename "$location")

  if [ -d "$HOME/$name" ]; then
    rm -rf "$HOME/$name"
  fi

  ln -nsf "$location" "$HOME/$name"
  echo -e "  Linked ${BLUE}$name${ENDCOLOR}"

done < <(find "$current_directory/home" -depth 1)
echo ""

echo -e "${YELLOW}Karabiner stuff...${ENDCOLOR}"
ln -nsf "$current_directory/misc/karabiner.xml" "$HOME/Library/Application Support/Karabiner/private.xml"
echo -e "  Linked ${BLUE}private.xml${ENDCOLOR}"
ln -nsf "$current_directory/misc/orgs.pqrs.Karabiner.plist" "$HOME/Library/Preferences/org.pqrs.Karabiner.plist"
echo -e "  Linked ${BLUE}plist${ENDCOLOR}"
echo ""

source ~/.bash_profile
