console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'yellow'
    template = "{{ .Path }}"

    [blocks.segments.properties]
      style = 'agnoster_short'
      max_depth = 2

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    background = 'transparent'
    foreground_templates = ["{{if or (.Working.Changed) (.Staging.Changed)}}red{{else}}green{{end}}"]
    template = " {{ .HEAD }}{{if or (gt .Behind 0) (gt .Ahead 0)}} <blue>[</>{{ if gt .Behind 0 }}<red>{{ .Behind }}</>{{ end }}{{if and (gt .Behind 0) (gt .Ahead 0)}}<grey>,</>{{end}}{{ if gt .Ahead 0 }}<green>{{ .Ahead }}</>{{ end }}<blue>]</>{{end}}"

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}blue{{end}}",
    ]
    foreground = 'blue'
    background = 'transparent'
    template = " ❯"
